### ISSUE TITLE
Add social media links and such

### ISSUE THREAD

**Issue by jalvarado91** [floridahackers/fh-platform#6]
Would be great to add links to our social media places. 

- Facebook Group/Page
- Twitter
- Medium
- GitHub 

and the "Made with <3 by Florida Hackers" footer mark like in the [Floatie](http://floatie.floridahackers.com/) site

**Comment by Techforchange** [comment]
@jalvarado91 Can I try? :)

**Comment by omar1893** [comment]
Sure where do you want it?

**Comment by elishaukpong** [comment]
I got here through Hacktoberfest on twitter! I'm new to open sourcing (skill level: intermediate, still taking lessons).
I'll love to contribute here and I'll appreciate any guidance!

**Comment by Techforchange** [comment]
@omar1893 Is there a specific file you want me to add the links or anywhere in the code?

**Comment by rsm23** [comment]
Working on it

**Comment by raviigarg** [comment]
On desktop:
![screenshot 2](https://user-images.githubusercontent.com/31215399/31026266-6cfe3824-a563-11e7-8e8d-5e16eddb14e0.png)
![screenshot 3](https://user-images.githubusercontent.com/31215399/31026267-6db89f8e-a563-11e7-9f6e-59de0a25f26f.png)
on small screen sizes:
![screenshot 6](https://user-images.githubusercontent.com/31215399/31026538-82ce039a-a564-11e7-8b43-f5f7a48c42a9.png)
I have done like this.
Social media icons have effect also.
I hope you will like my work. :)

**Comment by jalvarado91** [comment]
Thanks @garg-ravi24 , The footer mark looks great! 

Would you mind trying to put the social media icons on the footer? We don't want them to take too much attention from the top. 

Also, I realize I didn't specify a design guideline, or reference, but could you use the svg's from 
[here](http://svgicons.sparkk.fr/) and the medium svg icon? They should be good in white, without the circle around them. 

Thank you for taking the time to do this!

**Comment by raviigarg** [comment]
Sure..

**Comment by raviigarg** [comment]
What about this??
Icons are of svg format.

![screenshot 8](https://user-images.githubusercontent.com/31215399/31043334-6cc9a00e-a5d7-11e7-980a-d3f965488755.png)
